version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/eslint-plugin-react-pug

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn global add greenkeeper-lockfile

      - run: yarn install

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: ~/.yarn/bin/greenkeeper-lockfile-update

      - run: yarn lint

      - run: yarn test --recursive

      - run: ~/.yarn/bin/greenkeeper-lockfile-upload
